# Generated by Django 2.2.3 on 2019-07-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Safari_sys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authinfo',
            name='username',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
