# Generated by Django 2.2.3 on 2019-07-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Safari_sys', '0002_auto_20190710_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authinfo',
            name='mail',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
