# Generated by Django 2.2.3 on 2019-07-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Safari_sys', '0003_auto_20190714_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authinfo',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='authinfo',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='authinfo',
            old_name='p_code',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='authinfo',
            name='mail',
        ),
        migrations.AddField(
            model_name='authinfo',
            name='email',
            field=models.EmailField(default='a', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
