# Generated by Django 2.2.3 on 2019-07-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField(max_length=100)),
                ('seats_left', models.CharField(max_length=100)),
                ('depature', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
