# Generated by Django 2.2.3 on 2019-07-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdata',
            name='route_id',
            field=models.IntegerField(),
        ),
    ]
