# Generated by Django 2.2.3 on 2019-07-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Safari_sys', '0004_auto_20190714_1324'),
        ('booking', '0003_auto_20190723_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdata',
            name='str_route',
            field=models.CharField(default='ffff', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateField()),
                ('time_booked', models.TimeField()),
                ('route_id', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Safari_sys.AuthInfo')),
            ],
        ),
    ]
