# Generated by Django 2.2.3 on 2019-07-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20190725_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='teansacrion_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
