# Generated by Django 2.2.3 on 2019-07-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booked_teansacrion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='teansacrion_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='booked',
            name='departure_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booked',
            name='departure_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
